### ISSUE TITLE
mail-client/thunderbird needs mozcoreconf-v3.eclass

### ISSUE THREAD

**Issue by dirk-olmes** [hhoffstaette/portage#3]
We've had this before ...

Calculating dependencies / * ERROR: mail-client/thunderbird-38.8.0::hhoff failed (depend phase):
 *   mozcoreconf-v3.eclass could not be found by inherit()

**Comment by hhoffstaette** [comment]
Thanks for the reminder - it was already fixed, I just had not pushed yet. :)
It's up now.
